# Generated by Django 5.1.3 on 2024-12-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_password_users_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pwd',
            new_name='password',
        ),
    ]
